GSoC 2018: Final Report - MagickPlot
SciRuby/sciruby.com pull request #60
Opened 2019-01-28 09:11 UTC by Arafatk

2019-01-28 09:29 UTC, prasunanand approved these changes

2019-01-29 01:34 UTC, v0dro requested changes

2019-01-29 01:34 UTC, v0dro commented on source/_posts/2019-01-17-gsoc-2018-Ruby-Matplotlib.markdown
> +Matplotlib architecture is mostly written in Python with some of its backend (the renderer AGG and Figure canvas ) written in C++ ( The original AGG backend and helper scripts, which is quite tightly
```suggestion
Matplotlib architecture is mostly written in Python with some of its backend (the renderer AGG and Figure canvas ) written in C++ ( The original AGG backend and helper scripts, which is quite tightly bound to python). But recently the backends are also written in Python using the renderers which have Python APIs. The finer details of the Architecture can be found [here](https://www.aosabook.org/en/matplotlib.html).
```

2019-01-29 01:34 UTC, v0dro commented on source/_posts/2019-01-17-gsoc-2018-Ruby-Matplotlib.markdown
> +source community. I really appreciate the effort by Google Open Source Committee for conducting GSoC every year. It is the best platform for the aspiring programmers to improve their skill and give b
```suggestion
source community. I really appreciate the effort by Google Open Source Committee for conducting GSoC every year. It is the best platform for aspiring programmers to improve their skill and give back to society by developing free and open source software.
```

2019-01-30 09:28 UTC, prasunanand commented
@Arafatk , Wrap it up. Make the changes.

2019-01-30 09:30 UTC, arafatkatze commented
@prasunanand  Sorry for the delay.       
I hope this is okay.

2019-01-30 09:31 UTC, merged